# Generated by Django 4.0.5 on 2022-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('uid', models.IntegerField(null=True)),
                ('car_num', models.CharField(max_length=20, null=True)),
                ('car_num_short', models.IntegerField(null=True)),
                ('tsm', models.CharField(max_length=5, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('vel', models.FloatField(null=True)),
                ('lat_old', models.FloatField(null=True)),
                ('lng_old', models.FloatField(null=True)),
                ('zone', models.CharField(max_length=200, null=True)),
                ('in_zoneList', models.IntegerField(null=True)),
                ('airport_msg_time', models.CharField(max_length=200, null=True)),
                ('airport_msg', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(null=True)),
                ('Material', models.CharField(max_length=100, null=True)),
                ('Mass', models.FloatField(null=True)),
                ('Contrag', models.CharField(max_length=100, null=True)),
                ('Stock', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(null=True)),
                ('Material', models.CharField(max_length=100, null=True)),
                ('Mass', models.FloatField(null=True)),
                ('Contrag', models.CharField(max_length=100, null=True)),
                ('Car_Num', models.CharField(max_length=20, null=True)),
                ('PBA', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
