# Generated by Django 4.0.5 on 2022-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_driver_income_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_num_short',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
