# Generated by Django 4.0.5 on 2022-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_driver_car_num_alter_driver_car_num_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='coor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('uid', models.IntegerField(null=True)),
                ('car_num', models.CharField(max_length=20, null=True)),
                ('car_num_short', models.IntegerField(null=True)),
                ('tsm', models.CharField(max_length=5, null=True)),
                ('car_driver', models.CharField(max_length=50, null=True)),
                ('car_driver_short', models.CharField(max_length=100, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('vel', models.FloatField(null=True)),
                ('lat_old', models.FloatField(null=True)),
                ('lng_old', models.FloatField(null=True)),
                ('zone', models.CharField(max_length=200, null=True)),
                ('in_zoneList', models.IntegerField(null=True)),
                ('airport_msg', models.CharField(max_length=200, null=True)),
                ('airport_msg_time', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
