# Generated by Django 4.0.5 on 2022-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_coor_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coor',
            name='isTask',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='rope_ZoneCoorList',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='task_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='task_cur',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='task_full_coor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='task_full_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='task_left_coor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='task_left_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='task_right_coor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='task_right_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='y_km',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='y_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coor',
            name='y_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
